import { db } from '../db.js';
import { escapeHtml, toast, fmtDate, openModal, closeModal } from '../utils.js';

export async function renderMemory(root) {
  const [lockedFacts, canonNotes, memoryEntries] = await Promise.all([db.getAll('lockedFacts'), db.getAll('canonNotes'), db.getAll('memoryEntries')]);
  memoryEntries.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  root.innerHTML = `<h2 class="section-title">Memory</h2><p class="section-hint">Highest-priority locked facts, permanent canon, and continuity memory generated after each chapter.</p><div class="card"><h3>🔒 Locked facts — highest priority</h3><p class="muted">Always included, even if another document contradicts them.</p><div id="locked-list"></div><label class="field-label">Add locked fact</label><div class="card-row" style="gap:8px;"><input type="text" id="locked-new-input" placeholder="Example: Anya is a child; her vocabulary and reasoning should sound age-appropriate."><button class="btn btn-primary btn-sm" id="locked-add-btn">Add</button></div></div><div class="card"><h3>📜 Permanent canon</h3><p class="muted">Long-term background notes that must always be respected (story summaries, established relationships, etc.).</p><div id="canon-list"></div><label class="field-label">Add canon note</label><textarea id="canon-new-input" placeholder="Paste a permanent canon summary or fact here..."></textarea><div class="btn-row"><button class="btn btn-primary btn-sm" id="canon-add-btn">Add</button></div></div><div class="card"><h3>🧵 Chapter continuity memory</h3><p class="muted">Generated when a chapter is completed. If missing (for example, if the chapter is a draft or the request failed), go to Chapters and choose “🧠 Create / update memory” for that chapter. Review the summary before continuing.</p><div id="continuity-list"></div></div>`;
  renderLocked(lockedFacts, root); renderCanon(canonNotes, root); renderContinuity(memoryEntries, root);
  document.getElementById('locked-add-btn').addEventListener('click', async () => { const input = document.getElementById('locked-new-input'); const text = input.value.trim(); if (!text) return; await db.put('lockedFacts', { text, isCore: false }); input.value = ''; renderMemory(root); });
  document.getElementById('canon-add-btn').addEventListener('click', async () => { const input = document.getElementById('canon-new-input'); const text = input.value.trim(); if (!text) return; await db.put('canonNotes', { text, createdAt: new Date().toISOString() }); input.value = ''; renderMemory(root); });
}
function renderLocked(lockedFacts, root) { const el = document.getElementById('locked-list'); if (!lockedFacts.length) { el.innerHTML = `<p class="muted">No locked facts yet.</p>`; return; } el.innerHTML = lockedFacts.map((f) => `<div class="list-item" data-id="${f.id}"><div class="card-row"><span>${escapeHtml(f.text)}</span><button class="btn btn-danger btn-sm act-del">Remove</button></div>${f.isCore ? '<span class="pill pill-canon">core rule</span>' : ''}</div>`).join(''); el.querySelectorAll('.list-item').forEach((item) => { item.querySelector('.act-del').addEventListener('click', async () => { if (!confirm('Remove this locked fact?')) return; await db.del('lockedFacts', item.dataset.id); renderMemory(root); }); }); }
function renderCanon(canonNotes, root) { const el = document.getElementById('canon-list'); if (!canonNotes.length) { el.innerHTML = `<p class="muted">No canon notes yet.</p>`; return; } el.innerHTML = canonNotes.map((n) => `<div class="list-item" data-id="${n.id}"><div class="card-row"><span style="white-space:pre-wrap;">${escapeHtml(n.text)}</span><button class="btn btn-danger btn-sm act-del">Remove</button></div></div>`).join(''); el.querySelectorAll('.list-item').forEach((item) => { item.querySelector('.act-del').addEventListener('click', async () => { if (!confirm('Remove this canon note?')) return; await db.del('canonNotes', item.dataset.id); renderMemory(root); }); }); }
function renderContinuity(memoryEntries, root) { const el = document.getElementById('continuity-list'); if (!memoryEntries.length) { el.innerHTML = `<p class="muted">No continuity memory has been generated yet.</p>`; return; } el.innerHTML = memoryEntries.map((m) => `<div class="list-item" data-id="${m.id}"><div class="title-row"><b>${escapeHtml(m.chapterTitle || 'Chapter')}</b><span class="muted">${fmtDate(m.createdAt)}</span></div><button class="btn btn-ghost btn-sm act-view">View / edit</button><button class="btn btn-danger btn-sm act-del">Delete</button></div>`).join(''); el.querySelectorAll('.list-item').forEach((item) => { const id = item.dataset.id; item.querySelector('.act-view').addEventListener('click', async () => { const m = await db.get('memoryEntries', id); openMemoryEditModal(m, root); }); item.querySelector('.act-del').addEventListener('click', async () => { if (!confirm('Delete this continuity memory?')) return; await db.del('memoryEntries', id); renderMemory(root); }); }); }
function openMemoryEditModal(m, root) { const fields = [['events','EVENTS'],['relationshipChanges','RELATIONSHIP CHANGES'],['newFacts','NEW FACTS'],['whoKnowsWhat','WHO KNOWS WHAT'],['physicalState','PHYSICAL STATE / INJURIES'],['currentLocationTime','CURRENT LOCATION / TIME'],['openThreads','OPEN THREADS']]; openModal(`<h3 style="font-family:'Cormorant Garamond',serif; color:var(--oldrose-700);">${escapeHtml(m.chapterTitle)}</h3>${fields.map(([key,label]) => `<label class="field-label">${label}</label><textarea class="mem-field" data-key="${key}">${escapeHtml(m[key] || '')}</textarea>`).join('')}<div class="btn-row"><button class="btn btn-primary" id="mem-save-btn">Save</button><button class="btn btn-ghost" id="mem-cancel-btn">Close</button></div>`); document.getElementById('mem-cancel-btn').addEventListener('click', closeModal); document.getElementById('mem-save-btn').addEventListener('click', async () => { document.querySelectorAll('.mem-field').forEach((ta) => { m[ta.dataset.key] = ta.value.trim(); }); await db.put('memoryEntries', m); toast('Memory updated.'); closeModal(); renderMemory(root); }); }
