import { db } from '../db.js';
import { toast, escapeHtml } from '../utils.js';
import { listProviders } from '../providers/index.js';

export async function renderSettings(root) {
  const settings = (await db.get('settings', 'main')) || { provider: 'gemini', apiKeys: {}, models: {}, blockWordSize: 900 };
  const providers = listProviders();
  root.innerHTML = `<h2 class="section-title">Ajustes</h2><p class="section-hint">Tu API key se guarda SOLO en este navegador (IndexedDB) — nunca se escribe en el código ni se sube a ningún repositorio.</p><div class="card"><h3>Proveedor de IA</h3><label class="field-label">Proveedor activo</label><select id="s-provider">${providers.map((p) => `<option value="${p.id}" ${settings.provider === p.id ? 'selected' : ''}>${p.label}</option>`).join('')}</select><div id="provider-fields"></div><label class="field-label">Tamaño de bloque de generación (palabras por llamada a la IA)</label><input type="number" id="s-blocksize" value="${settings.blockWordSize || 900}" min="300" max="2000"><p class="muted">Los capítulos largos se generan en varios bloques de este tamaño; cada bloque se guarda antes de pedir el siguiente, así que puedes cerrar la web y continuar luego.</p><div class="btn-row"><button class="btn btn-primary" id="s-save-btn">Guardar ajustes</button></div></div><div class="card"><h3>Copia de seguridad</h3><p class="muted">Exporta o importa todo (capítulos, personajes, documentos, memoria) como un archivo JSON.</p><div class="btn-row"><button class="btn btn-ghost" id="s-export-btn">⬇️ Exportar backup completo</button><label class="btn btn-ghost" style="cursor:pointer;">⬆️ Importar backup<input type="file" id="s-import-input" accept="application/json" style="display:none;"></label></div></div>`;
  function renderProviderFields() { const p = document.getElementById('s-provider').value; const field = document.getElementById('provider-fields'); const key = settings.apiKeys?.[p] || ''; const model = settings.models?.[p] || (p === 'gemini' ? 'gemini-2.0-flash' : p === 'openrouter' ? 'openrouter/free' : 'gpt-4o'); field.innerHTML = `<label class="field-label">API key de ${providers.find((x) => x.id === p)?.label}</label><input type="password" id="s-apikey" value="${escapeHtml(key)}" placeholder="Pega aquí tu API key" autocomplete="off"><label class="field-label">Modelo</label><input type="text" id="s-model" value="${escapeHtml(model)}" placeholder="ej: openrouter/free / gemini-2.0-flash">${p === 'openrouter' ? '<p class="muted">🌸 Para escribir fanfics, prueba <b>arcee-ai/trinity-large-preview:free</b>. <code>openrouter/free</code> elige modelos gratuitos al azar y algunos pueden devolver una respuesta vacía. También puedes usar otros IDs acabados en <code>:free</code>; no admite modelos de pago. <a href="https://openrouter.ai/settings/keys" target="_blank" rel="noopener noreferrer">Crear clave gratuita de OpenRouter ↗</a>. La clave de Gemini no sirve aquí. Los modelos gratuitos pueden tener límites y saturación.</p>' : ''}`; }
  renderProviderFields(); document.getElementById('s-provider').addEventListener('change', renderProviderFields);
  document.getElementById('s-save-btn').addEventListener('click', async () => { const fresh = (await db.get('settings', 'main')) || { id: 'main', apiKeys: {}, models: {} }; const p = document.getElementById('s-provider').value; fresh.provider = p; fresh.apiKeys = { ...fresh.apiKeys, [p]: document.getElementById('s-apikey').value.trim() }; fresh.models = { ...fresh.models, [p]: document.getElementById('s-model').value.trim() }; fresh.blockWordSize = parseInt(document.getElementById('s-blocksize').value, 10) || 900; fresh.id = 'main'; await db.put('settings', fresh); toast('Ajustes guardados.'); });
  document.getElementById('s-export-btn').addEventListener('click', async () => { const dump = await db.exportAll(); const blob = new Blob([JSON.stringify(dump, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `power-to-strive-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url); });
  document.getElementById('s-import-input').addEventListener('change', async (e) => { const file = e.target.files[0]; if (!file) return; if (!confirm('Importar reemplazará todos los datos actuales de la app. ¿Continuar?')) return; try { const text = await file.text(); const dump = JSON.parse(text); await db.importAll(dump, { merge: false }); toast('Backup importado. Recargando…'); setTimeout(() => location.reload(), 1000); } catch (err) { toast('No se pudo importar: ' + err.message, { error: true }); } });
}
