import { db } from '../db.js';
import { toast, escapeHtml } from '../utils.js';
import { listProviders } from '../providers/index.js';
import { renderAppearanceSettings, bindAppearanceSettings } from './appearance.js';

export async function renderSettings(root) {
  const settings = (await db.get('settings', 'main')) || { provider: 'gemini', apiKeys: {}, models: {}, blockWordSize: 900 };
  const providers = listProviders();
  root.innerHTML = `<h2 class="section-title">Settings</h2>${renderAppearanceSettings()}<p class="section-hint">Your API key is saved ONLY in this browser (IndexedDB). It is never added to the source code or uploaded to a repository.</p><div class="card"><h3>AI provider</h3><label class="field-label">Active provider</label><select id="s-provider">${providers.map((p) => `<option value="${p.id}" ${settings.provider === p.id ? 'selected' : ''}>${p.label}</option>`).join('')}</select><div id="provider-fields"></div><label class="field-label">Generation block size (words per AI request)</label><input type="number" id="s-blocksize" value="${settings.blockWordSize || 900}" min="300" max="2000"><p class="muted">Long chapters are generated in blocks of this size. Each approved block is saved before the next request, so you can close the app and continue later.</p><div class="btn-row"><button class="btn btn-primary" id="s-save-btn">Save settings</button></div></div><div class="card"><h3>Backup & restore</h3><p class="muted">Export or import all your chapters, characters, documents, and memory as a JSON file. Your full backup may include API keys: keep it private.</p><div class="btn-row"><button class="btn btn-ghost" id="s-export-btn">⬇️ Export full backup</button><label class="btn btn-ghost" style="cursor:pointer;">⬆️ Import backup<input type="file" id="s-import-input" accept="application/json" style="display:none;"></label></div></div>`;
  function renderProviderFields() { const p = document.getElementById('s-provider').value; const field = document.getElementById('provider-fields'); const key = settings.apiKeys?.[p] || ''; const model = settings.models?.[p] || (p === 'gemini' ? 'gemini-2.0-flash' : p === 'openrouter' ? 'openrouter/free' : 'gpt-4o'); field.innerHTML = `<label class="field-label">API key for ${providers.find((x) => x.id === p)?.label}</label><input type="password" id="s-apikey" value="${escapeHtml(key)}" placeholder="Paste your API key here" autocomplete="off"><label class="field-label">Model</label><input type="text" id="s-model" value="${escapeHtml(model)}" placeholder="e.g. openrouter/free / gemini-2.0-flash">${p === 'openrouter' ? '<p class="muted">🌸 For writing fanfiction, try <b>arcee-ai/trinity-large-preview:free</b>. <code>openrouter/free</code> selects free models at random, and some may return an empty response. You may also use other model IDs ending in <code>:free</code>; paid models are not supported. <a href="https://openrouter.ai/settings/keys" target="_blank" rel="noopener noreferrer">Get a free OpenRouter key ↗</a>. Your Gemini key will not work here. Free models may have rate limits or be busy.</p>' : ''}`; }
  bindAppearanceSettings();
  renderProviderFields(); document.getElementById('s-provider').addEventListener('change', renderProviderFields);
  document.getElementById('s-save-btn').addEventListener('click', async () => { const fresh = (await db.get('settings', 'main')) || { id: 'main', apiKeys: {}, models: {} }; const p = document.getElementById('s-provider').value; fresh.provider = p; fresh.apiKeys = { ...fresh.apiKeys, [p]: document.getElementById('s-apikey').value.trim() }; fresh.models = { ...fresh.models, [p]: document.getElementById('s-model').value.trim() }; fresh.blockWordSize = parseInt(document.getElementById('s-blocksize').value, 10) || 900; fresh.id = 'main'; await db.put('settings', fresh); toast('Settings saved.'); });
  document.getElementById('s-export-btn').addEventListener('click', async () => { const dump = await db.exportAll(); const blob = new Blob([JSON.stringify(dump, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `inky-paws-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url); });
  document.getElementById('s-import-input').addEventListener('change', async (e) => { const file = e.target.files[0]; if (!file) return; if (!confirm('Importing this backup will REPLACE all current app data, including every story and its settings. Continue?')) return; try { const text = await file.text(); const dump = JSON.parse(text); await db.importAll(dump, { merge: false }); toast('Backup imported. Reloading…'); setTimeout(() => location.reload(), 1000); } catch (err) { toast('Could not import backup: ' + err.message, { error: true }); } });
}
